### ISSUE TITLE
When starting a payment using simulated reader, an expired API key is thrown

### ISSUE THREAD

**Issue by brunoambr** [stripe/stripe-terminal-react-native#605] opened 2024-01-04 19:10 UTC
**Describe the bug**
When starting a payment using simulated reader, an expired API key error is thrown. Error occurs sporadically and does not happen in every device. It happens very quickly if simultaneous payments are made.

**To Reproduce**

1. Start "StripeTerminalProvider" with a simulated reader.
2. Error should occur sporadically.
3. When trying again, the error is not thrown and Tap to Pay operation completes successfully.

**Expected behavior**
Error should not occur, because it resolves automatically by trying again. I suspect that it is related to StripeTerminalProvider's token auto management.

**Screenshots**
![image](https://github.com/stripe/stripe-terminal-react-native/assets/8863164/3c33288e-51c5-432b-bc33-b44be40857c8)

**Stripe Terminal React Native SDK version**

- `^0.0.1-beta.14`

**Smartphone (please complete the following information):**

- Device: iPhone 11
- OS: iOS 17.2.1

**Comment by nazli-stripe** [comment] 2024-01-17 19:09
@brunoambr is this your simulated reader for Tap to Pay on iPhone? I wasn't able to repro it on my device. Can you try it out with the latest version `0.0.1-beta.15` or using our example or dev-app, and let us know if you run into the issue there as well?

**Comment by brunoambr** [comment] 2024-01-19 17:20
@nazli-stripe Yes, it is my simulated reader (iPhone device). But it happens using an iOS simulator too.

I was able to reproduce using dev-app and 0.0.1-beta.15.

![Screenshot 2024-01-19 at 14 12 01](https://github.com/stripe/stripe-terminal-react-native/assets/8863164/d0be47c5-cf92-46de-9bbf-56549b6b6ceb)

Steps to reproduce:

- Run two projects instances (for example, a simulator and a physical device) and try to start a payment simultaneously (using the same API test key).

- Sometimes, one of the readers will disconnect unexpectedly (it could happen at any step, I was able to reproduce while creating a payment intent or processing it) and the expired API key error should be the cause.

**Comment by nazli-stripe** [comment] 2024-02-08 21:27
> Run two projects instances (for example, a simulator and a physical device) and try to start a payment simultaneously (using the same API test key).

Do you mean the same connection token? Each token is only supposed to be used with one instance. Your `tokenProvider` should return a new ConnectionToken every time it's called

**Comment by Brunowilliang** [comment] 2024-03-14 14:05
Hello @brunoambr, I'm experiencing the same issue. After completing a payment and waiting for about one minute, attempting to make another payment results in the following error:
```shell
[Error: Expired API Key provided: pss_test_YW*********************************************************************_******kinr]
```
This consistently occurs after the mentioned time interval.

**Comment by brunoambr** [comment] 2024-03-25 16:30
@Brunowilliang I'm not using the simulated reader anymore, so the error is not thrown. I couldn't find another alternative.

**Comment by dmatthews-stripe** [comment] 2024-05-07 18:36
Hi @brunoambr , we will be closing this ticket for now since we cannot reproduce. Feel free to reopen if this becomes a pressing issue again.

**Closed by dmatthews-stripe** 2024-05-07 18:36 UTC

**Comment by nicolasdevienne** [comment] 2026-01-02 10:04
Hi @nazli-stripe @dmatthews-stripe and Happy New Year! I’m still seeing the same issue with the latest SDK version 0.0.1-beta.28: immediately after a successful connection, I try to retrieve a PaymentIntent using the retrievePaymentIntent function and the client_secret, but a "SessionExpired" error is triggered—even though the connection to the reader was just established. It works again after restarting the app and creating a new token. The issue seems to occur somewhat randomly.
