### ISSUE TITLE
UnexpectedSdkError in IOS 18 Beta

### ISSUE THREAD

**Issue by arjunAbcd** [stripe/stripe-terminal-react-native#807] opened 2024-09-09 10:56 UTC
**Describe the bug**

Getting error  {"code": "UnexpectedSdkError", "message": "An unexpected SDK error occurred."} while making payment through mPOS machine and only if amount greater than $999.99 .Otherwise if amount less than $999.99, it works well. No issues on Android.
Found this issue only on IOS 18 Beta .
I have been using the beta version 0.0.1-beta.13 and tested by updating to beta 0.0.1-beta.20 (latest) , issue still exists.

**To Reproduce**

To reproduce - By making transaction through mPOS machine and the amount should be greater than $999.99 

![Screenshot 2024-09-09 at 11 51 04 AM](https://github.com/user-attachments/assets/d4ca09d2-32b4-4008-80c0-1b813a4ed1a2)

**Stripe Terminal React Native SDK version**

- ^0.0.1-beta.20

**Smartphone :**
- Tested Device:  Iphone Xs Max 
- OS: iOS 18 Beta

**Comment by nazli-stripe** [comment] 2024-09-12 00:15
hey @arjunAbcd this is due to a bug our SDK has on iOS 18. We are working on a hotfix release for this week specifically targeting this issue.

**Comment by nazli-stripe** [comment] 2024-09-13 05:39
beta.21 was just released and addresses this issue. Can you give it a try and let us know if you are still running into it?

**Comment by Eonfuzz** [comment] 2024-09-17 00:45
> @arjunAbcd: beta.21 was just released and addresses this issue. Can you give it a try and let us know if you are still running into it?

We're seeing a similar error for iOS devices when calling CollectPayment.

Our steps to reproduce:
1. We connect to the localmobile reader after login (This works fine)
2. When we reach the collectPaymentMethod stage when taking payments, the useStripTerminal hook
onDidReportUnexpectedReaderDisconnect throws the following error:
{"message":"Reader has been disconnected unexpectedly","code":"UnexpectedSdkError"}
3. The collectPaymentMethod stalls and sits there indefinitely as it cannot take payments.

We've reproduced this on:
IPhone 13, ios version 17.2.1
https://github.com/stripe/stripe-terminal-react-native@v0.0.1-beta.21

Any idea on how we could further debug / get access to the internal sdk error?

**Comment by arjunAbcd** [comment] 2024-09-17 04:46
> @arjunAbcd: beta.21 was just released and addresses this issue. Can you give it a try and let us know if you are still running into it?
Thanks for the update @nazli-stripe , I will check and update

**Comment by arjunAbcd** [comment] 2024-09-17 05:54
> @arjunAbcd: beta.21 was just released and addresses this issue. Can you give it a try and let us know if you are still running into it?

Tested on IOS 18 Beta and IOS 15.0 , it working fine now with beta.21

**Comment by arjunAbcd** [comment] 2024-09-17 06:04
> > @arjunAbcd: beta.21 was just released and addresses this issue. Can you give it a try and let us know if you are still running into it?
> 
> We're seeing a similar error for iOS devices when calling CollectPayment.
> 
> Our steps to reproduce:
> 
> 1. We connect to the localmobile reader after login (This works fine)
> 2. When we reach the collectPaymentMethod stage when taking payments, the useStripTerminal hook
>    onDidReportUnexpectedReaderDisconnect throws the following error:
>    {"message":"Reader has been disconnected unexpectedly","code":"UnexpectedSdkError"}
> 3. The collectPaymentMethod stalls and sits there indefinitely as it cannot take payments.
> 
> We've reproduced this on: IPhone 13, ios version 17.2.1 https://github.com/stripe/stripe-terminal-react-native@v0.0.1-beta.21
> 
> Any idea on how we could further debug / get access to the internal sdk error?

Are you getting the mentioned error on other IOS version/device ?

**Comment by nazli-stripe** [comment] 2024-09-17 16:24
@Eonfuzz i think what you are reporting is a different issue than what @arjunAbcd is describing. Do you mind opening a new issue and include serial number for the device you are using so we can take a look? 

The SDK had a known bug with amounts over 99999 on iOS 18 which has been fixed with beta.21 release now as confirmed by @arjunAbcd so closing this issue.

**Closed by nazli-stripe** 2024-09-17 16:24 UTC
Labels: bug

**Comment by Eonfuzz** [comment] 2024-09-18 00:08
> @Eonfuzz i think what you are reporting is a different issue than what @arjunAbcd is describing. Do you mind opening a new issue and include serial number for the device you are using so we can take a look?
> 
> The SDK had a known bug with amounts over 99999 on iOS 18 which has been fixed with beta.21 release now as confirmed by @arjunAbcd so closing this issue.

Thanks Nazli. it was a customer issue failing to describe the error correctly. v21 solved my issue too.
