### ISSUE TITLE
iOS Production Build Field to Discover Reader & Connect Reader From India. Verify the app has the necessary entitlements and that the application bundle is valid.

### ISSUE THREAD

**Issue by abhijitCN** [stripe/stripe-terminal-react-native#725] opened 2024-06-10 12:26 UTC
**ERROR: Verify the app has the necessary entitlements and that the application bundle is valid**
iOS Production Build Field to Discover Reader & Connect the Reader From India. I already added the required Capabilities in Xcode.

**Following Steps**
1.  Uses Bluetooth LE accessories.
2. added com.apple.developer.proximity-reader.payment.acceptance key in capability.
3. Added Near Field Communication Tag Reading (Tag-Specific Data Protocol (TAG)).

**Expected behavior**
NFC communication not establish.

**Screenshots**
![error1](https://github.com/stripe/stripe-terminal-react-native/assets/113179261/cd7add82-8cd7-4093-b94a-d58561688a13)
![Screenshot 2024-06-10 at 5 08 28 PM](https://github.com/stripe/stripe-terminal-react-native/assets/113179261/0f4e5e6d-ed49-492d-9f9f-2433071038ad)
![Screenshot 2024-06-10 at 5 06 36 PM](https://github.com/stripe/stripe-terminal-react-native/assets/113179261/ad183588-5ab1-4b6b-a7cd-7fe613265cf3)

**Stripe Terminal React Native SDK version**
- (e.g., `^0.0.1-beta.18`)

**Smartphone (please complete the following information):**
- Device: [e.g. iPhone11]
- OS: [e.g. iOS17.5.1]

**Additional context**
@nazli-stripe  can you please look into this and assist me

**Comment by nazli-stripe** [comment] 2024-06-11 22:16
@abhijitCN did you get a chance to review this thread: https://github.com/stripe/stripe-terminal-react-native/issues/594#issuecomment-1895909363

**Comment by zeulb** [comment] 2024-06-12 18:45
@nazli-stripe This is also an issue for us, I had confirmed the bundle has the necessary entitlement

**Comment by nazli-stripe** [comment] 2024-06-20 16:43
@abhijitCN looks like you are missing the entitlement for `com.apple.developer.proximity-reader.payment.acceptance`.  The NFC entitlement is not needed for Terminal and can be removed, unless you need it for your app in general. 

@zeulb looks like @bric-stripe responded to you in the other issue

**Comment by abhijitCN** [comment] 2024-06-24 10:53
I need assistance with handling a reader's disconnection after a successful payment. Specifically, I'm looking to:
Disconnect the reader once the payment is successful.
Reconnect the reader after the payment process is complete.

Is there a function or method available to control this functionality? Any guidance or examples would be greatly appreciated.

Thank you @nazli-stripe

**Comment by nazli-stripe** [comment] 2024-10-24 21:51
hey @abhijitCN can you create a new issue for reader disconnection question? Closing this one as entitlement issue seems to have resolved.

**Closed by nazli-stripe** 2024-10-24 21:51 UTC
Labels: ttp
