### ISSUE TITLE
Unable to reconnect to the same reader - Connection Token already redeemed

### ISSUE THREAD

**Issue by usamamoinakhter** [stripe/stripe-terminal-react-native#377] opened 2022-09-06 22:38 UTC
**Describe the bug**
After disconnecting from the stripe M2 reader, I cannot reconnect to the same device. It throws The Stripe Terminal ConnectionToken has already been redeemed. The documentation suggested that I should call ` clearCachedCredentials() `after disconnecting in order to generate a new connection-token but it still throws the same error. I was successfully able to reconnect after restarting the application though.

**To Reproduce**

1. Discover Readers
2. Connect to a reader
3. Disconnect connection with the reader
4. Discover Again
5. Connect with the same reader 

**Expected behavior**
The device should be connected to the same reader again

**Smartphone (please complete the following information):**

- Device: Lenovo TB-X606F
- OS: Android Version 10
- SDK Version 0.0.1-beta.8

**Comment by bric-stripe** [comment] 2022-09-09 19:08
Hi @usamamoinakhter I'm trying to reproduce but wanted to confirm: When attempting the second connect is your connection token provider receiving the request for another token? Or are you not even seeing that request for a new connection token?

Is there possibly any caching at that layer? The expectation is the SDK should request another connection token from your connection token provider when attempting to connect the second time. If the same connection token was returned in the second call due to any caching that would exhibit this same error.

**Comment by bric-stripe** [comment] 2022-09-09 20:54
I just confirmed using our example-app and watching logs in my merchant backend for that that when I disconnect and reconnect it fetches a new connection token. I was using android on a pixel 3 but wouldn't expect any device specific issues here. Are you able to reproduce the error using the example app?

**Comment by usamamoinakhter** [comment] 2022-09-12 01:52
Hey @bric-stripe , thank you for the response.
This is the code we have been using
  ```
 const fetchTokenProvider = async (): Promise<string> => {
        console.log("Fetching Token");
        const response = await call({
            url: `${servicesConst.serviceEndpoints.STRIPE_TOKEN}`,
            method: servicesConst.serviceMethods.POST,
            params: {
                store_id: storeId
            },
        });
        if (!response)
            return "";
        const { secret } = response as StripeToken;
        return secret;
    };
```


```
            <StripeTerminalProvider
                logLevel="verbose"
                tokenProvider={fetchTokenProvider}>
                <Auth />
            </StripeTerminalProvider>
```

I don't think the token is cached. The problem is I see the log only the first time, the second time the function doesn't even get called. I will check against example-app and see if it works fine or not.

**Comment by b13i** [comment] 2022-09-15 03:48
We're running into the same issue and have almost the same code as @usamamoinakhter. To reproduce, I sometimes have to disconnect/reconnect multiple times.

**Comment by claudelama-solet** [comment] 2022-09-15 21:16
@bric-stripe Do you have an updates on this?

**Comment by bric-stripe** [comment] 2022-12-02 18:14
@usamamoinakhter @claudelama-solet apologies for the delay getting back to this.

I'm still unable to reproduce the problem, both with and without calling `clearCachedCredentials` (though for the use case here that shouldn't be necessary to force it to refresh the connection token).

Does the issue reproduce 100% of the time when connect > disconnect > connect again and it repros? If not, how frequently are you seeing this? Is it after some amount of time between connecting and disconnecting? Note the M2 will reset itself every 24h for PCI compliance which will cause a disconnect but should be able to be reconnected to right away and should request a fresh connection token.

Are you able to reproduce the error using the example app from the repo? The sample code provided seems correct but knowing if it works in the example app can hopefully help us hunt for differences and/or ideally get a repro from the example app that we can debug/fix.

Also, could you provide an M2 serial number and rough timing of when you hit the `connection token already redeemed` issue? With that we can look through some logs to see if anything stands out.

**Comment by claudetradearcadetv** [comment] 2022-12-05 22:12
@bric-stripe We had put a workaround in place since then. When we had the issue, it was 100% reproducible.
We could reproduce it when power cycling the reader. What we saw at the time is that the SDK was never calling our function.

I can't speak as to why you can't reproduce the issue on your hand using the sample app. The date of the issue was between Sept 4 and September 15. One of the reader that exhibited the issue was STRM26139015920

**Comment by claudelama-solet** [comment] 2022-12-05 22:14
@bric-stripe We had put a workaround in place since then. When we had the issue, it was 100% reproducible.
We could reproduce it when power cycling the reader. What we saw at the time is that the SDK was never calling our function.

I can't speak as to why you can't reproduce the issue on your hand using the sample app. The date of the issue was between Sept 4 and September 15. One of the reader that exhibited the issue was STRM26139015920

**Comment by bric-stripe** [comment] 2022-12-05 22:46
> We had put a workaround in place since then

thanks, could you explain the work around you ended up with? Knowing that may help me realize what I'm missing in my attempts to reproduce the problem.

**Comment by claudelama-solet** [comment] 2022-12-05 23:32
As every time we tried to reconnect we were getting `connection token already redeemed`, we reset the list of discovered readers and launched a new discovery. This is to the best of what I can recall as we did this 3 months ago... I am looking at the code as I write this and it looks foreign to me right now :-)

**Comment by claudetradearcadetv** [comment] 2022-12-05 23:39
@bric-stripe confirmed. I dug deeper in the code and I confirm that we reset the client secret to null and launch a new discovery.

**Comment by billfinn-stripe** [comment] 2023-01-04 18:55
I'm going to close this issue, as we are not able to reproduce, and you seem to have a workaround. If you encounter it again, let us know, and we'll investigate further.

**Closed by billfinn-stripe** 2023-01-04 18:55 UTC
